"""Operations owns sequencing; adapters own processes and filesystem effects."""

from dataclasses import dataclass
from typing import ContextManager, Protocol


@dataclass(frozen=True, slots=True)
class Release:
    identity: str
    schema_min: int = 5
    schema_max: int = 5


@dataclass(frozen=True, slots=True)
class Outcome:
    release: str
    result: str
    stage: str
    rollback: str = "not_needed"


class DeploymentPort(Protocol):
    def lock(self) -> ContextManager[None]: ...
    def current(self) -> Release | None: ...
    def build(self, revision: str) -> Release: ...
    def preflight(self, release: Release) -> None: ...
    def test(self, release: Release) -> None: ...
    def compatible(self, release: Release) -> None: ...
    def backup(self, release: Release) -> None: ...
    def publish(self, release: Release) -> None: ...
    def stop(self) -> None: ...
    def activate(self, release: Release) -> None: ...
    def start(self) -> None: ...
    def ready(self, release: Release) -> None: ...
    def smoke(self, release: Release) -> None: ...
    def retain(self, release: Release, previous: Release | None) -> None: ...
    def discard(self, release: Release) -> None: ...
    def audit(self, operation: str, release: str, result: str, reason: str) -> None: ...


class ManualPort(Protocol):
    async def accept(self, operation: str, receipt: str) -> str: ...


class Responder(Protocol):
    async def reply(self, text: str, *, ephemeral: bool) -> None: ...
