"""Watch-web persistence and transport-neutral process contracts."""

from typing import Protocol
from discordbot.watch.domain.policy import Cleanup, Intent, Invite
from discordbot.watch.ports.repository import WatchPlaylistData


class Writer(Protocol):
    async def start(self, epoch: str, now: float) -> None: ...
    async def heartbeat(self, epoch: str, now: float) -> None: ...
    async def release(self, epoch: str) -> None: ...
    async def create(self, epoch: str, intent: Intent, now: float) -> Intent: ...
    async def bind(self, epoch: str, session_id: str, channel: int, message: int, admin: bool, now: float) -> None: ...
    async def close(self, epoch: str, session_id: str, now: float) -> None: ...
    async def abort(self, epoch: str, intent: Intent, now: float) -> None: ...
    async def playlist(self, epoch: str, session_id: str, now: float) -> tuple[WatchPlaylistData, ...]: ...
    async def add(self, epoch: str, session_id: str, url: str, title: str, by: str, now: float, maximum: int) -> None: ...
    async def remove(self, epoch: str, session_id: str, url: str, now: float) -> None: ...
    async def cleanup(self, epoch: str, now: float) -> tuple[Cleanup, ...]: ...
    async def acknowledge(self, epoch: str, session_id: str, now: float) -> None: ...


class Capability(Protocol):
    def mint(self, guild: int, user: int, operation: str, issued: int) -> tuple[str, str]: ...
    def digest(self, token: str) -> str: ...


class Metadata(Protocol):
    async def title(self, video_id: str) -> str: ...
    async def close(self) -> None: ...


class Socket(Protocol):
    async def send(self, message: dict[str, object]) -> None: ...
    async def close(self, code: int) -> None: ...


class Control(Protocol):
    async def call(self, operation: str, data: dict[str, object]) -> dict[str, object]: ...
